server:
  port: 8888

encrypt:
  key: alp
spring:
  application:
    name: conf-service
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
  profiles:
    active: native

  actuator:
    endpoints:
      web:
        exposure:
          include: '*'
    endpoint:
      health:
        show-details: always
      info:
        enabled: true

  security:
    user:
      name: alp
      password: alp
